### ISSUE TITLE
Connecting when cluster has password

### ISSUE THREAD

**Issue by yatender-oktalk** [zhongwencool/redix-cluster#2]
How to connect to cluster when it is protected by password, which key I should give in config?
I'm not able to connect when I'm giving my key as `password`, 
when I'm using redix library it's getting connected properly with single instance.

someone please help me out here.

```

config :redix_cluster,
  cluster_nodes: [
    %{host: "host01.com", port: 6379},
    %{host: "host02.com", port: 6379},
    %{host: "host03.com", port: 6379},
    %{host: "host04.com", port: 6379},
    %{host: "host05.com", port: 6379},
    %{host: "host06.com", port: 6379}
  ],
  password: "password",
  pool_size: 5,
  pool_max_overflow: 10,
  socket_opts: [],
  backoff: 2000,
  max_reconnection_attempts: nil
```

**Comment by zhongwencool** [comment]
https://github.com/zhongwencool/redix-cluster/blob/bf063beba3127f5a7adb68b584097951fd11bcb7/lib/redix_cluster/worker.ex#L16-L17

beacuse I don't pass the password option.

You can modify it by yourself, since I don't use redis cluster any more.

**Comment by yatender-oktalk** [comment]
Thank you for your response.
I'll modify the source code.
